library("rpart")
samp1 = rnorm(n=100, mean=5, sd=2)
samp2 = rnorm(n=100, mean=-5, sd=2)
df1 = data.frame(X=samp1, Y=as.factor(1))
df2 = data.frame(X=samp2, Y=as.factor(0))
data_df = rbind(df1, df2)
tree1 = rpart(Y~X, data = data_df, method = "class")
samp3 = rnorm(n=100, mean=1, sd=2)
samp4 = rnorm(n=100, mean=-1, sd=2)
df3 = data.frame(X=samp3, Y=as.factor(1))
df4 = data.frame(X=samp4, Y=as.factor(0))
data_df = rbind(df3, df4)
tree2 = rpart(Y~X, data = data_df, method = "class")
